const {chromium}=require('C:/Users/DELL/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:"msedge"}); const page=await browser.newPage({viewport:{width:1440,height:1100}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:5173/',{waitUntil:'networkidle'});
 await page.getByText('Records connected',{exact:true}).waitFor({timeout:30000});
 fs.mkdirSync('outputs',{recursive:true});await page.screenshot({path:'outputs/desktop.png',fullPage:true});
 await page.getByRole('button',{name:'WorkerSafe',exact:true}).click();
 await page.getByRole('button',{name:'Load synthetic crew',exact:true}).click();
 await page.getByText('T. Moyo',{exact:true}).waitFor();
 await page.reload({waitUntil:'networkidle'});await page.getByText('T. Moyo',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Start muster',exact:true}).click();await page.getByLabel('Title / name',{exact:true}).fill('QA muster');await page.getByRole('button',{name:'Save preview record',exact:true}).click();
 await page.getByText('QA muster',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Confirm accounted for',exact:true}).first().click();
 await page.getByRole('button',{name:'Inspections',exact:true}).click();await page.getByRole('button',{name:'Log inspection',exact:true}).click();await page.getByLabel('Title / name',{exact:true}).fill('QA inspection');await page.getByLabel('Original due date / time',{exact:true}).fill('2026-09-14T09:00');await page.getByLabel('Findings / rationale',{exact:true}).fill('Synthetic inspection finding for software acceptance.');await page.getByRole('button',{name:'Save preview record',exact:true}).click();await page.getByText('QA inspection',{exact:true}).waitFor();
 await page.getByRole('button',{name:'MineShield',exact:true}).click();await page.getByRole('button',{name:'Open incident',exact:true}).click();await page.getByLabel('Title / name',{exact:true}).fill('QA response drill');await page.getByLabel('Response notes',{exact:true}).fill('Simulated incident; no external action.');await page.getByRole('button',{name:'Save preview record',exact:true}).click();await page.getByText('QA response drill',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Foresight Lite',exact:true}).click();await page.getByRole('button',{name:'New buddy check-in',exact:true}).click();await page.getByLabel('Title / name',{exact:true}).fill('QA shaft');await page.getByLabel('Fictional buddy contact',{exact:true}).fill('Demo buddy');await page.getByLabel('Expected return',{exact:true}).fill('2026-09-13T10:00');await page.getByLabel('Registered headcount',{exact:true}).fill('2');await page.getByRole('button',{name:'Save preview record',exact:true}).click();await page.getByText('QA shaft',{exact:true}).waitFor();await page.getByRole('button',{name:'Record demo notification',exact:true}).first().click();
 await page.getByRole('button',{name:'Simulator lab',exact:true}).click();await page.getByLabel('Single water factor',{exact:true}).fill('100');await page.getByText('Water trend contribution: 25.0',{exact:false}).waitFor();
 await page.getByLabel('Replay scenario',{exact:true}).selectOption('wet-control');await page.waitForTimeout(1200);await page.screenshot({path:'outputs/simulator.png',fullPage:true});
 await page.getByRole('button',{name:'Command Centre',exact:false}).first().click();await page.getByLabel('Replay scenario',{exact:true}).selectOption('wet');await page.waitForTimeout(800);await page.getByRole('button',{name:'Review factors & response',exact:false}).first().click();await page.getByRole('tab',{name:'Retained peak',exact:true}).click();await page.screenshot({path:'outputs/evidence.png',fullPage:true});await page.getByRole('tab',{name:'Human response',exact:true}).click();await page.getByRole('button',{name:'Record human response',exact:true}).click();await page.getByLabel('Findings / rationale',{exact:true}).fill('Named human review of the simulator evidence.');await page.getByRole('button',{name:'Save preview record',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'outputs/mobile.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 console.log(JSON.stringify({errors,mobileOverflow:overflow,workflows:'worker persistence, muster, inspection, incident, lite outbox, replay, evidence panels'},null,2));
 await browser.close();if(errors.length||overflow)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
